### ISSUE TITLE
求分享资源

### ISSUE THREAD

**Issue by aclihub** [CatAndCoffee/playground#1]
小萌新一个，对python并不了解，折腾一下午也还是根本不会用
能否把资源分享出来，百度云来一个？

**Comment by CatAndCoffee** [comment]
呃……当时下的图片我看完就删掉了，不过百度云上应该有其他人共享的吧:smiley:

**Comment by CatAndCoffee** [comment]
确实我那个代码当时也没想着会有人看，就没写文档
你看看这个，我觉得应该就知道怎么用了https://www.jianshu.com/p/ccec00913bec
python还是比较容易看懂的（虽然我写的一点都不规范）
@aclihub
